name: Deploy Website

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # This gives the action permission to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for peaceiris/actions-gh-pages

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          enable_jekyll: false
